class CitiesList {
  static final List<dynamic> allCities = [
    'Tokyo',
    'Jakarta',
    'Delhi',
    'Guangzhou',
    'Mumbai',
    'Manila',
    'Shanghai',
    'São Paulo',
    'Seoul',
    'Mexico City',
    'Cairo',
    'New York',
    'Dhaka',
    'Beijing',
    'Kolkata',
    'Bangkok',
    'Shenzhen',
    'Moscow',
    'Buenos Aires',
    'Lagos',
    'Istanbul',
    'Karachi',
  ];
}